### ISSUE TITLE
Label and LabelNote position (question or enhancement)

### ISSUE THREAD

**Issue by florimm** [pritishvaidya/react-native-speedometer#2]
Because I display speedometer small I need to display Label and LabelNot side by side like:
100 - Moderate
or
Moderate (100)
so it the Speedometer wont take vertical space.
Is this possible ?

**Comment by pritishvaidya** [comment]
Yes, there are three styles available that'll help you fix it.
The styles can be used in this way to make it in a row.
```
      <RNSpeedometer
          // ... other props
          labelWrapperStyle={{ flexDirection: 'row',  justifyContent: 'center' }}
          labelStyle={{ fontSize: 14 }}
          labelNoteStyle={{ fontSize: 14 }}
        />
```
 For a `-` in between value and label you can modify the `labels` property to include a _hiphen_ as 

```
  [
    {
      name: '- Too Slow',
      labelColor: '#ff2900',
      activeBarColor: '#ff2900',
    },
    {
      name: '- Very Slow',
      labelColor: '#ff5400',
      activeBarColor: '#ff5400',
    },
 ]
```
