### ISSUE TITLE
Animated: `useNativeDriver` was not specified rn v0.62+

### ISSUE THREAD

**Issue by kabus202** [pritishvaidya/react-native-speedometer#29]
Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false` 
    in Speedometer

**Comment by MateusVT** [comment]
Plss, could you guys fix that?

**Comment by nkryzano** [comment]
Also looking for a fix. Would be much appreciated!

**Comment by Ninjinka** [comment]
just add useNativeDriver : true to animation in index

**Comment by Akshay-RK** [comment]
Hey anyone please let me know how to get this update into the node_modules folder, After **npm i react-native-speedometer --save** command, I am getting the same issue.
Please let me know how to get this updated package into my project

**Comment by Ninjinka** [comment]
Resolution is merged but npm package is not published

**Comment by Akshay-RK** [comment]
> Resolution is merged but npm package is not published

So how can I Get the resolved version of the same,
