### ISSUE TITLE
Cannot read property 'labelColor' of undefined

### ISSUE THREAD

**Issue by ph98** [pritishvaidya/react-native-speedometer#3]
hi 
i installed the package using yarn 
but got this error 

![image](https://user-images.githubusercontent.com/6303786/53678919-bfce0d80-3cda-11e9-854e-36d24660c43f.png)

version i'm using  : 
    "react-native-speedometer": "^1.0.2",

thank you a lot for helping me ! :-)

**Comment by pritishvaidya** [comment]
Hello @ph98 ,
Can you post the code that you implemented using this package?

Thanks

**Comment by ph98** [comment]
i also see that there is an error in import statement
![image](https://user-images.githubusercontent.com/6303786/53679512-9e711f80-3ce2-11e9-945f-07acf8d181b6.png)

i used this code ( tried with and without props ) :
`<SafeAreaView style={{flex:1}}>
        <RNSpeedometer value={this.state.temp} size={200}
            
            defaultValue={50}
            minValue={0}
            maxValue={100}
            easeDuration={500}
            labels= {[{
              name: 'Pathetically weak',
              labelColor: '#ff2900',
              activeBarColor: '#ff2900'
            }, {
              name: 'Very weak',
              labelColor: '#ff5400',
              activeBarColor: '#ff5400'
            }]}
            
        />
      </SafeAreaView>`

**Comment by pritishvaidya** [comment]
Here's a working [snack expo link](https://snack.expo.io/@pritishvaidya94/rn-speedometer-example) with the almost same code, not sure what might be wrong with your code

**Comment by bilalseh** [comment]
Please run this code:

`import * as React from 'react';
import { TextInput, View, StyleSheet } from 'react-native';
import RNSpeedometer from 'react-native-speedometer';


export default class App extends React.Component {
  state = {
    value: 100,
  };

  onChange = value => this.setState({ value: parseInt(value) });

  render() {
    return (
      <View style={styles.container}>
        <TextInput placeholder="Speedometer Value" style={styles.textInput} onChangeText={this.onChange} />
        <RNSpeedometer value={this.state.value}
        size={200}
        defaultValue={50}
        minValue={50}
        maxValue={100}
        easeDuration={500}
        labels= {[{
          name: 'Pathetically weak',
          labelColor: '#ff2900',
          activeBarColor: '#ff2900'
        }, {
          name: 'Very weak',
          labelColor: '#ff5400',
          activeBarColor: '#ff5400'
        }]}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  textInput: {
    borderBottomWidth: 0.3,
    borderBottomColor: 'black',
    height: 25,
    fontSize: 16,
    marginVertical: 50,
    marginHorizontal: 20,
  }
});
`

**Comment by bilalseh** [comment]
Please run this code:
```import * as React from 'react';
import { TextInput, View, StyleSheet } from 'react-native';
import RNSpeedometer from 'react-native-speedometer';


export default class App extends React.Component {
  state = {
    value: 100,
  };

  onChange = value => this.setState({ value: parseInt(value) });

  render() {
    return (
      <View style={styles.container}>
        <TextInput placeholder="Speedometer Value" style={styles.textInput} onChangeText={this.onChange} />
        <RNSpeedometer value={this.state.value}
        size={200}
        defaultValue={50}
        minValue={50}
        maxValue={100}
        easeDuration={500}
        labels= {[{
          name: 'Pathetically weak',
          labelColor: '#ff2900',
          activeBarColor: '#ff2900'
        }, {
          name: 'Very weak',
          labelColor: '#ff5400',
          activeBarColor: '#ff5400'
        }]}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  textInput: {
    borderBottomWidth: 0.3,
    borderBottomColor: 'black',
    height: 25,
    fontSize: 16,
    marginVertical: 50,
    marginHorizontal: 20,
  }
});
```

You will get the same error mentioned above.

**Comment by pritishvaidya** [comment]
Thanks,
I'll take a look as soon as possible.
