### ISSUE TITLE
How to Add Any Extra Character on Labels, like Percentage (%)

### ISSUE THREAD

**Issue by ManiruzzamanAkash** [pritishvaidya/react-native-speedometer#34]
I want to put additional %, or any additional character on the  speedometer.
Means - in value, I can pass any numeric value and that's good.
**Now, I want to display that like this - 33%**

Is there any way to do that ?

**Comment by umarphaarook** [comment]
This [Pull Request](https://github.com/pritishvaidya/react-native-speedometer/pull/35) will help when it's merged.

Example:
`<RNSpeedometer value={(value) => '${value}%'} size={200} />`

I hope that helps ^^

**Comment by rajanZoxima** [comment]
no this is not working

**Comment by anoopjangra90** [comment]
Try following style 

labelStyle={{ height: 0, width: 0 }}  
OR
labelWrapperStyle={{ height: 0, width: 0 }}



and add your own custom  text component
