### ISSUE TITLE
wrapperStyle and circleStyle all these object not working, how to reduce thikness of circle and how to % in number showing 

### ISSUE THREAD

**Issue by rajanZoxima** [pritishvaidya/react-native-speedometer#37]
wrapperStyle and circleStyle all these object not working, how to reduce thikness of circle and how to % in number showing

**Comment by pritishvaidya** [comment]
Can you provide a minimal example of what you are using https://snack.expo.io/ `wrapperStyle and circleStyle all these object not working`

**Comment by rajanZoxima** [comment]
import RNSpeedometer from 'react-native-speedometer'

const TargetIndicator = (props) => {
let values = parseInt(((props.value) / (props.target)) * 100)
return (
<SafeAreaView style={styles.container}>

<RNSpeedometer
value={values}
labelWrapperStyle={{ height: 0, width: 0 }}
style={styles.outerCircleStyle}

labels={[
{
name: 'ACHIEVED',
labelColor: '#d6211d',
activeBarColor: '#d6211d',
},
// {
// name: 'ACHIEVED',
// labelColor: '#d6211d',
// activeBarColor: '#d6211d',
// },
{
name: 'ACHIEVED',
labelColor: '#FBA503F8',
activeBarColor: '#FBA503F8',
},
{
name: 'ACHIEVED',
labelColor: '#0C9307',
activeBarColor: '#0C9307',
},
]}
maxValue={100}
size={hp('35%')} />

**Comment by pritishvaidya** [comment]
There is no prop for `style` in this library. You can either check the [properties](https://github.com/pritishvaidya/react-native-speedometer#properties) or send a working [snack](https://snack.expo.io/) example

**Comment by rajanZoxima** [comment]
if i want to make circle thinner what should i do?

**Comment by pritishvaidya** [comment]
You need to increase the height and width of inner circle in proportion
