### ISSUE TITLE
Getting useNativeDriver warning and animation is laggy

### ISSUE THREAD

**Issue by dhksrini** [pritishvaidya/react-native-speedometer#40]
How to fix this warning:

- Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`
I have tried passing this as props. But still no use. How to fix this issue. Thanks

**Comment by pritishvaidya** [comment]
It is already specified by default as `true` in the package.

Can you provide the version and code of what you are using ?
