### ISSUE TITLE
How I can create a gradient color ??

### ISSUE THREAD

**Issue by minh-dai** [pritishvaidya/react-native-speedometer#41]

**Comment by pritishvaidya** [comment]
I don't think gradient is supported by the package with current changes. It needs an additional PR for it. Gradient can be created with react-native-linear-gradient

**Comment by nguyentrannhan** [comment]
hello @pritishvaidya , i mean like this.
![Screen Shot 2021-01-08 at 13 20 12](https://user-images.githubusercontent.com/17939754/103981343-37610380-51b4-11eb-85df-4de223c1a604.png)

**Comment by minh-dai** [comment]
hello @pritishvaidya, 
![Screen Shot 2021-01-08 at 13 20 12](https://user-images.githubusercontent.com/24986640/103981430-5fe8fd80-51b4-11eb-9fb4-c4330361f5c5.png)
I mean like this

**Comment by pritishvaidya** [comment]
It requires the native package to work even for sub level gradients which is not supported right now.

**Comment by nguyentrannhan** [comment]
thank you so much @pritishvaidya

**Comment by minh-dai** [comment]
@pritishvaidya thank you so much.
