### ISSUE TITLE
RTL Speedometer

### ISSUE THREAD

**Issue by human2012** [pritishvaidya/react-native-speedometer#42]
Hello, can you do something to work on the rtl react-native-speedometer too?
<img width="316" alt="Снимок экрана 2021-01-22 в 09 57 24" src="https://user-images.githubusercontent.com/15163748/105463098-3cd04a80-5c98-11eb-93b3-0d429ce4e4be.png">

**Comment by aashu22451** [comment]
I am facing the same issue only on Android in Arabic Mode How can I fix this 
@human2012
