### ISSUE TITLE
Speedometer does not touch left end when value is minimum. Similarly speedometer does not touch right end when value is maximum

### ISSUE THREAD

**Issue by mohity777** [pritishvaidya/react-native-speedometer#43]

**Comment by pritishvaidya** [comment]
The speedometer needle is based on the image and only transitions from 180deg to -180 deg. You can add custom style to the needle to be positioned lower to align with the speedometer section

**Comment by mohity777** [comment]
Yeah i figured it out by changing the style of animated.view which wrapped the image component and putting it outside of the inclosing view.
