### ISSUE TITLE
Size per color and Decimal Value (Question)

### ISSUE THREAD

**Issue by EduMOliveira** [pritishvaidya/react-native-speedometer#5]
Hi, I would like to know if it is possible to set a value size for each color. 
Example:
![Screen Shot 03-20-19 at 03 39 AM](https://user-images.githubusercontent.com/43083901/54666075-91687480-4ac7-11e9-8d4d-d8d5177fb69f.PNG)

And I would also like to know if it is possible to print the value with decimal numbers like this example: 
![Screen Shot 03-20-19 at 03 42 AM](https://user-images.githubusercontent.com/43083901/54666088-99281900-4ac7-11e9-9589-85232c358ef0.PNG)

**Comment by pritishvaidya** [comment]
Unfortunately, as a speedometer works, the value that you set in the properties is equally split based on the labels provided. So currently there is no provision to scale it based on the values.

I'll add a minor update for decimal values up to two digits when get time to work on it.

**Comment by pritishvaidya** [comment]
The prop `allowedDecimals` will be available in the latest version [1.0.3](https://www.npmjs.com/package/react-native-speedometer)
